spring:
  r2dbc:
    url: r2dbc:postgres://localhost:5432/pbxmanager
    username: user
    password: pass
  liquibase:
    url: jdbc:postgresql://localhost:5432/pbxmanager
    user: user
    password: pass

tellows:
  api-url: https://www.tellows.com/basic
  api-key-md5: 399a147c51f6942600fa41412f2678d1
  country: pt
  language: pt

server:
  servlet:
    context-path: /api

---

spring:
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: r2dbc:postgres://${POSTGRES_HOST:host.docker.internal}:5432/pbxmanager
  liquibase:
    url: jdbc:postgresql://${POSTGRES_HOST:host.docker.internal}:5432/pbxmanager
